_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
action_noise:
    value: 0
collection_steps:
    value: 100
eval_interval:
    value: 50
task_end:
    value:
        - 15
        - 20
task_start:
    value:
        - 0
        - 0
        - 0
train_steps:
    value: 100
waypoint:
    value:
        - 1
        - 2
